status/urls.py
from django.urls import path

from .views import (CreateStatus,
                    StatusDetailView,
                    StatusListView,
                    CustomSerarch,
                    UpdateStatusView,
                    DeleteStatusView,
                    adminSearchTask,adminDetailTask,
                    emailTask)

app_name = 'status'

urlpatterns = [
    path('create/', CreateStatus.as_view(),name = 'create'),
    path('detail/<int:pk>', StatusDetailView.as_view(),name = 'detail'),
    path('list/', StatusListView.as_view(),name = 'list'),
    path('search/', CustomSerarch,name = 'search'),
    path('update/<int:pk>', UpdateStatusView.as_view(),name = 'update'),
    path('delete/<int:pk>', DeleteStatusView.as_view(), name = 'delete'),
    path('admin/search/', adminSearchTask.as_view(),name='admin_search'),
    path('admin/detail/<int:pk>',adminDetailTask,name ='admin_detail'),
    path('email/',emailTask,name ='email'),
]

task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import (PasswordResetView,
                                        PasswordResetConfirmView,
                                        PasswordResetDoneView,
                                        PasswordResetCompleteView)

from .views import Home,test,thanks


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('status/',include("status.urls")),
    path('', Home , name = 'home'),
    path('test/', test, name='test'),
    path('thank/', thanks, name='thanks'),
    path('api/',include('accounts.api.accounts.urls')),
    path('password-reset/',PasswordResetView.as_view(template_name='reset.html'),name='reset'),
    path('password-reset/done',PasswordResetDoneView.as_view(template_name='done.html'),name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>',PasswordResetConfirmView.as_view(template_name='confirm.html'),name='password_reset_confirm'),
    path('password-reset/complete/',PasswordResetCompleteView.as_view(template_name='complete.html'),name='password_reset_complete'),
]

status/models.py
from django.db import models
from django.utils.timezone import now
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


class Tasks(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    starting_date = models.DateField(blank=True,default=now)
    percentange = models.IntegerField(default=0)
    detail = models.CharField(max_length=250)
    comment = models.CharField(max_length = 250,blank=True, default= ' ')

    def __str__(self):
        return self.detail
    
    def get_absolute_url(self):
        return reverse('status:detail', kwargs= {"pk":self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'percentange', 'updated_at']

    

status/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Tasks
User = get_user_model()

class StatusForm(forms.ModelForm):
    percentange = forms.IntegerField(required=True)
    starting_date = forms.DateField(required=True)
    class Meta:
        model = Tasks
        fields = [
            'detail',
            'starting_date',
            'percentange',
            'comment',
        ]
        widget = {
            'starting_date': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}),         
        }
    def clean(self,*args, **kwargs):
        detail = self.cleaned_data['detail']
        percent = self.cleaned_data['percentange']
        if detail == '' or None:
            raise forms.ValidationError("Deatil Cannot be Blank")
        if int(percent) > 100:
            raise forms.ValidationError("Enter correct percent")
        return super().clean(*args, **kwargs)

status/views.py
from datetime import date
import calendar
import pymsteams

from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
# from braces.views import SelectRelatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings

from .forms import StatusForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from .models import Tasks

User = get_user_model()


class CreateStatus(LoginRequiredMixin, CreateView):
    model = Tasks
    # fields = ('detail','starting_date','percentange','comment')
    template_name = 'status/tasks_form.html'
    form_class = StatusForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        firstname = str(self.request.user.first_name) + ' ' +str(self.request.user.last_name) 
        task = str(self.object.detail)
        date = str(self.object.starting_date)
        percent = str(self.object.percentange)
        comment = str(self.object.comment) + '</pre>'
        msg = "<pre> Task Name: " + task + '<br> Start Date :' + date +'<br> Percentage : ' + percent + '%' + '<br> Comment:' + comment
        team = pymsteams.connectorcard(settings.OUTLOOK_WEBHOOK)
        team.title(firstname)
        team.text(msg)
        team.send() 																							  			
        return super().form_valid(form)


class StatusDetailView(LoginRequiredMixin, DetailView):
    model = Tasks


class StatusListView(LoginRequiredMixin, ListView):
    model = Tasks

    def get_queryset(self):
        return Tasks.objects.filter(user__username__iexact=self.request.user).order_by('-updated_at')


class UpdateStatusView(LoginRequiredMixin, UpdateView):
    model = Tasks
    form_class = StatusForm
    template_name = 'status/tasks_form.html'


class DeleteStatusView(LoginRequiredMixin, DeleteView):
    model = Tasks
    success_url = reverse_lazy('status:list')


def CustomSerarch(request):
    query = dict(request.GET)
    if query:
        fromdate = (query.get('q'))[0]
        todate = query.get('q')[1]
        qs = Tasks.objects.filter(Q(created_at__gte=fromdate) &
                                  Q(created_at__lte=todate) & (Q(user__username__iexact=request.user) or Q(
            user__id__iexact=pk))).order_by('-updated_at')
        return render(request, 'status/tasks_list.html', {'object_list': qs})
    return render(request, 'status/tasks_list.html', {})


class adminSearchTask(LoginRequiredMixin, ListView):
    model = User
    template_name = 'status/user_list.html'


def adminDetailTask(request, pk):
    qs = Tasks.objects.filter(user__id__iexact=pk)
    return render(request, 'status/tasks_list.html', {'object_list': qs})


def emailTask(request):
    query = dict(request.GET)
    if query:
        fromdate = (query.get('q'))[0]
        todate = query.get('q')[1]
        qs = Tasks.objects.filter(Q(created_at__gte=fromdate) &
                                  Q(created_at__lte=todate) & (Q(user__username__iexact=request.user))).order_by(
            'created_at')
        data = ''
        # for i in list(qs.values()):
        #     print(calendar.day_name[i['created_at'].weekday()])

        try:
            day = None
            for i in list(qs.values()):
                if calendar.day_name[i['created_at'].weekday()] != day:
                    data += '\n' + 'Date:' + i['created_at'].strftime("%d-%m-%Y") + ' : ' + str(
                        calendar.day_name[i['created_at'].weekday()] + '\n')
                    day = calendar.day_name[i['created_at'].weekday()]
                data += ('Task Name:' + i['detail'] + '\n' +
                         'Started Date:' + i['starting_date'].strftime("%d-%m-%Y") + '\n' +
                         'Percent:' + str(i['percentange']) + "%" + '\n \n')
            print(data)
            task = "Task from : " + list(qs.values())[0]['created_at'].strftime("%d-%m-%Y") + " to : " + list(qs.values())[-1]['created_at'].strftime("%d-%m-%Y")
            admin = 'admin@mail.com'
            send_mail(subject=task,
                      message=data,
                      from_email=request.user.email,
                      recipient_list=[admin, request.user.email])
        except IndexError:
            data = "No record Found"
            return render(request, 'status/email_task.html', {'message': "No record found to email"})
        return render(request, 'status/email_task.html', {
            'message': "The mail has been send to " + request.user.email + ' and ' + admin})
    return render(request, 'status/email_task.html', {})

task/views.py
from django.shortcuts import render
from datetime import date
from django.contrib.auth import get_user_model
from status.models import Tasks

User  = get_user_model()

def Home(request):
    qs = Tasks.objects.filter(created_at=date.today())
    return render(request, 'home.html',{"today_detail":qs})


def test(request):
    return render(request, 'test.html',)


def thanks(request):
    return render(request, 'thanks.html',)

status/templates/status/email_task.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h3 style="margin-left: 500px;">Email Task.</h3>
<br>
{% if request.user.is_staff == False %}
<form action="{% url 'status:email' %}" method="GET">
    <h4><strong>From Date :</strong>
        <input type="date" name="q" id="" value="{{request.GET.q}}" required>
        <strong>To Date   :</strong>
        <input type="date" name="q" id="" value="{{request.GET.q}}" required>
        <button type="submit">Email</button></h4>
</form>
{% endif %}
<br>
{{message}}
{% endblock %}

status/templates/status/status_base.html
<div class="container">
    <h3 style="margin-left: 300px;">Task List</h3>
    <div class="col-6" style="width: 500px; margin-left: 200px;">
        {% block subcontent %}

        {% endblock %}
    </div>
</div>

status/templates/status/tasks_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h3>Are You Want To Delete the Task?</h3>
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'status:detail' pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>
{% endblock %}

status/templates/status/tasks_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h3 style="margin-left: 500px;">Task Entry</h3>
<br>
<div class="col-6" style="width: 500px; margin-left: 50px;">
    <div class="container">
        <p><h4><strong>Name:</strong>              {{ object.user.first_name }}</h4></p>
        <p><h4><strong>Detail:</strong>              {{ object.detail }}</h4></p>
        <p><h4><strong>Percent:</strong>         {{ object.percentange }}%</h4></p>
        <p><h4><strong>Comment:</strong>           {{ object.comment }}</h4></p>
        <p>  <h1></h1>        </p>
        <p><h6><strong>Create at: </strong>{{object.created_at}}</h6></p>
        <p><h6><strong>Update at:</strong> {{object.updated_at}}</h6></p>
        {% if request.user == object.user  %}
        <a href="{% url 'status:update' pk=object.pk %}"><button class="btn btn-primary">Update</button></a>
        <a href="{% url 'status:delete' pk=object.pk %}"><button class="btn btn-primary">Delete</button></a>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

status/templates/status/tasks_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
<h3 style="margin-left: 300px;">Name :{{request.user.first_name}}</h3>
<div class="col-6" style="width: 500px; margin-left: 200px;">
<form method="POST" class="row">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class = 'btn btn-primary' type="submit">Create/Update</button>
</form>
</div>
</div>
{% endblock %}

status/templates/status/tasks_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h3 style="margin-left: 500px;">Task List.</h3>
<br>
{% if request.user.is_staff == False %}
<form style="margin-left: 250px;" action="{% url 'status:search' %}" method="GET" >
    <h4><strong>From Date :</strong>
        <input type="date" name="q" id="" value="{{request.GET.q}}" required>
        <strong>To Date   :</strong>
        <input type="date" name="q" id="" value="{{request.GET.q}}" required>
        <button class = 'btn btn-success' type="submit">Search</button></h4>
</form>
{% endif %}
<br>
<div class="col-2" style="width: 500px; margin-left: 50px;">
    {% if object_list.count != 0 %}
    
        {% for item in object_list %}
        <div class="container">
            <h5><p><strong>Task Detail:    </strong>{{item.detail}}</p></h5>
            <h5><p><strong>Starting Date:  </strong>{{item.starting_date}}</p></h5>
            <h5><p><strong>Percent:        </strong>{{item.percentange}}%</p></h5>
            <h5><strong>Update at:         </strong> {{item.updated_at}}</h5>
            <a href="{% url 'status:detail' pk=item.pk %}">detail...</a>
            <hr style="width:100%;text-align:left;margin-left:0">
        </div>
        {% endfor %}
    </div>
    {% else %}
        <p>Nothing to Display</p>
    {% endif %}
</div>
</div>
{% endblock %}

status/templates/status/user_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h3 style="margin-left: 300px;">User List</h3>
<br>
<div class="col-6" style="width: 500px; margin-left: 200px;">
    {% for item in object_list %}
        {% if not item.is_staff %}
            <ol>
                <h4><a href="{% url 'status:admin_detail' pk=item.pk %}">{{item.first_name}}</a></h4>
            </ol>         
        {% endif %}
    {% endfor %}
    </div>
</div>
</div>
{% endblock %}