accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView ,
                                        LogoutView,
                                        LogoutView)
# from django.contrib.auth.views import 

from .views import AccountCreationView,change_password,success

app_name = 'accounts'


urlpatterns = [
    path('create/',AccountCreationView.as_view(),name ='create'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path('change_password/',change_password,name = 'change_password'),
    path('success/',success,name="success"),
]

status/urls.py
from django.urls import path

from .views import (CreateStatus,
                    StatusDetailView,
                    StatusListView,
                    CustomSerarch,
                    UpdateStatusView,
                    DeleteStatusView,
                    adminSearchTask,adminDetailTask,
                    emailTask)

app_name = 'status'

urlpatterns = [
    path('create/', CreateStatus.as_view(),name = 'create'),
    path('detail/<int:pk>', StatusDetailView.as_view(),name = 'detail'),
    path('list/', StatusListView.as_view(),name = 'list'),
    path('search/', CustomSerarch,name = 'search'),
    path('update/<int:pk>', UpdateStatusView.as_view(),name = 'update'),
    path('delete/<int:pk>', DeleteStatusView.as_view(), name = 'delete'),
    path('admin/search/', adminSearchTask.as_view(),name='admin_search'),
    path('admin/detail/<int:pk>',adminDetailTask,name ='admin_detail'),
    path('email/',emailTask,name ='email'),
]

task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import (PasswordResetView,
                                        PasswordResetConfirmView,
                                        PasswordResetDoneView,
                                        PasswordResetCompleteView)

from .views import Home,test,thanks


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('status/',include("status.urls")),
    path('', Home , name = 'home'),
    path('test/', test, name='test'),
    path('thank/', thanks, name='thanks'),
    path('api/',include('accounts.api.accounts.urls')),
    path('password-reset/',PasswordResetView.as_view(template_name='reset.html'),name='reset'),
    path('password-reset/done',PasswordResetDoneView.as_view(template_name='done.html'),name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>',PasswordResetConfirmView.as_view(template_name='confirm.html'),name='password_reset_confirm'),
    path('password-reset/complete/',PasswordResetCompleteView.as_view(template_name='complete.html'),name='password_reset_complete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>Task Status</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


</head>
<body>
        <nav class="navbar  mynav" role="navigation" id="navbar">
                <div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Task Status</a>

                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                {% if request.user.is_staff == True %}
                                    <li><a href="{% url 'status:admin_search' %}" class="btn btn-simple">Search Task</a></li>
                                    <li><a href="{% url 'accounts:change_password' %}" class="btn btn-simple">Change Password</a></li>
                                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">logout</a></li>
                                
                                {% else %}
                                    <li><a href="{% url 'status:create' %}" class="btn btn-simple">Create</a></li>
                                    <li><a href="{% url 'status:list' %}" class="btn btn-simple">See task List</a>
                                    <li><a href="{% url 'status:email' %}" class="btn btn-simple">Email task List</a>
                                    <li><a href="{% url 'accounts:change_password' %}" class="btn btn-simple">Change Password</a></li>
                                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">logout</a></li>
                                {%endif %}
                            {% else %}
                                  <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                                  <li><a href="{% url 'accounts:create' %}" class="btn btn-simple">Sign up</a></li>
                            {% endif %}
                        </ul>
                </div>
            </nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>
</body>
</html>

templates/complete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h3>Password reset complete</h3>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'accounts:login' %}">Login</a>
{% endblock %}

templates/confirm.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <div class="container">
        <h3 style="margin-left: 50px;">Enter new password</h3>
        <div class="col-6" style="width: 500px; margin-left: 50px;">
        <form method="POST" class="row">
            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class = 'btn btn-primary' type="submit">Change my Passowd</button>
        </form>
        </div>
        </div>
{% endblock %}

templates/done.html
{% extends 'base.html' %}
{% block content %}
    
    <h3>Password reset sent</h3>
    <br>
<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
    <h1> Welcome {{ request.user.first_name }}.</h1>
    <br>
    <div class="container">
        <h3>Todays all tasks status</h3>
        <br>
    </div>
    <div class = 'container'>
        {% if today_detail.count != 0 %}
            {% for i in today_detail %}
            <ul>
                <h4><strong>{{i.user.first_name}}</strong></h4>
                <p><strong>Task Name: </strong>{{i.detail}}</p>
                <p><strong>Starting date: </strong>{{i.starting_date}}</p>
                <p><strong>Percentage: </strong> {{i.percentange}}% </p>
                <p><strong>Comment: </strong> {{i.comment}} </p>
            </ul>
            <br>
            {% endfor %}
        {% else %}
            <br><h6><p>Nothing To Display</p></h6>
        {% endif %}
    </div>
    {% else %}
    <h1> Welcome to the Home page.</h1>
    {% endif %}
    
{% endblock %}

templates/reset.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <div class="col-6" style="width: 500px; margin-left: 50px;">
        <form method="POST" class="row">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class = 'btn btn-primary' type="submit">Send Email</button>
        </form>
    </div>
</div>
{% endblock  %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks For Visiting</h1>
{% endblock %}